name: dart_orm_adapter_mongodb
version: 0.2.0
description: >
  MongoDB adapter for DartORM
author: Ustimenko Sergey <ustims@gmail.com>
homepage: http://github.com/ustims/DartORM-MongoDB
dependencies:
#  dart_orm: ^0.3.0
  dart_orm:
#    path: ../DartORM
    git:
      url: https://github.com/DartOrm/DartORM
      ref: upgrade-libraries-and-use-docker-compose
  logging: ^0.11.0
  mongo_dart: ^0.3.0
